import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import Navbar from "@/components/shared/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "BlogAI - Production Blogging Platform",
  description: "A full-stack blogging platform with AI summaries generated by Google Gemini.",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
        <Toaster position="top-right" />
        <Navbar />
        <main className="flex-1">
          {children}
        </main>
        <footer className="bg-white border-t py-12 mt-20">
          <div className="max-w-6xl mx-auto px-4 text-center">
            <p className="text-slate-400 text-sm font-medium">
              © {new Date().getFullYear()} BlogAI. Built with Next.js, Supabase, and Gemini AI.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
